- name: Call nested_cc_deploy for each peer
  include_tasks: nested_cc_deploy.yaml
  vars:
    channel_name: "{{ item.channel_name | lower }}"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
  loop: "{{ participants }}"
  loop_control:
    loop_var: participant
  when: participant.org_status == 'new' or participant.peerstatus is not defined or participant.peerstatus == 'new'
