# Check or Wait if install-chaincode is already run
- name: "Waiting for chaincode to be installed on {{ peer.name }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Job"
    namespace: "{{ org.name |lower }}-net"
    kubernetes: "{{ org.k8s }}"
    component_name: "installchaincode-{{ peer.name }}-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}"
    # component_name: "installchaincode-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: peer.chaincode is defined

# Get chaincode ID from namespace installation pod
- name: Copy the CCID from installation pod 
  shell: |
    export INSTALL_POD=$(KUBECONFIG={{ org.k8s.config_file }} kubectl get po -n {{ org.name }}-net | grep "installchaincode-peer0" | awk '{print $1}')
    export CHAINCODE_CCID=$(KUBECONFIG={{ org.k8s.config_file }} kubectl logs ${INSTALL_POD} -n {{ org.name }}-net --tail=10 | grep -o '{{ network.chaincode_name }}:[^,]*')
    echo $CHAINCODE_CCID
  register: ccid

- name: "Deploy external chaincode pods for {{ participant.name }}"
  include_role:
    name: helm_component
  vars:
    name: "external_chaincode"
    type: "external_chaincode"
    org_name: "{{ org.name | lower }}"
    component_name: "{{ participant.name }}-chaincode"
    component_ns: "{{ participant.name | lower}}-net"
    orderer: "{{ network.orderers | first }}"
    chaincode_ccid: "{{ ccid.stdout }}"
    extcc_image: "<Docker_User_Name>/basic:1.0"
    alpine_image: "{{ docker_url }}/alpine-utils:1.0"
    git_url: "{{ org.gitops.git_url }}"
    git_branch: "{{ org.gitops.branch }}"
    charts_dir: "{{ org.gitops.chart_source }}"
    vault: "{{ org.vault }}"
    values_dir: "{{playbook_dir}}/../../../{{org.gitops.release_dir}}/{{ org.name | lower }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer 
  when: peer.name == 'peer0'

  #Git Push : Pushes the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ org.gitops }}"
    GIT_RESET_PATH: "platforms/hyperledger-fabric/configuration"
    msg: "[ci skip] Pushing external chaincode files"
  tags:
    - notest

# Wait for peer pods to be in the state of running
- name: "Waiting for chaincode pod in {{ participant.name | lower }}-net"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ participant.name | lower }}-net"
    component_name: "{{ participant.name }}-chaincode"
    kubernetes: "{{ org.k8s }}"
    label_selectors:
      - app = external-chaincode
  tags:
    - notest