---
#######################################
# Master Playbook for the setting up and reseting the Blockchain Automation Framework DLT network
#######################################
- hosts: all

  tasks:
  # Get chaincode ID from namespace installation pod
  - name: Copy the CCID from installation pod 
    shell: |
      export INSTALL_POD=$(KUBECONFIG=/home/davidh/.kube/config kubectl get po -n carrier-net | grep "installchaincode" | awk '{print $1}')
      export CHAINCODE_CCID=$(KUBECONFIG=/home/davidh/.kube/config kubectl logs ${INSTALL_POD} -n carrier-net --tail=1 | grep -o 'marbles:[^,]*')
      echo $CHAINCODE_CCID
    register: ccid

  - name: CCID retrieved from installation pod {{ ccid.stdout }}
    ansible.builtin.debug:
      var: ccid
      verbosity: 2
